# Generated by Django 3.2 on 2021-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('degination', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m?%d')),
                ('facebook', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
